### PR TITLE
NewService API, simplify certificate loading and pushpackage signing APIs.

### LINKED ISSUE #22: Extract bundle-id from certificate
I've noticed that you can extract the bundle-id from the certificate and put it into the Headers as Topic (it seems to be required), so you can avoid asking for it.

```
cert, err := certificate.Load(filename, passphrase)
if err != nil {
    log.Fatal(err)
}

commonName := cert.Leaf.Subject.CommonName
bundle := strings.Replace(commonName, "Apple Push Services: ", "", 1)

headers := &push.Headers{
	Topic: bundle,
}
```

### PR DESCRIPTION
**Pull request by nathany**
* [x] NewService API extracts topic from cert, closes #22
* [x] pushpackage: use TLS cert for signing instead of x509 cert and privateKey
* [x] certificate: return TLS cert directly since it can be used for NewService and pushpackage.Sign
* [x] reorganize push code

### CODE REVIEW

**Comment by nathany** [comment]
@macteo Apologies in the delay in getting to this. Mind doing a quick code review? What do you think of  this for the API?

**Comment by nathany** [comment]
After making this change, I realized that I can simplify the `pkg.Sign` API to use `tls.Certificate`. I'm going to make those revisions on this branch.

**Comment by bolshoy** [comment]
@nathany  there still needs to be a way to specify the notification topic. For example, we have two topics, one regular and one voip. The certificate contains both topics, but when you send the notification you must put a specific topic. At the moment, Apple just adds ".voip" suffix to a voip topic, so a flag can also work.

**Comment by nathany** [comment]
Hm. Okay. So we need to add Topic back to Headers then.

**Pull request merged**
