### PR TITLE
apns-push-type header is required on iOS 13 and later

### PR DESCRIPTION
**Pull request by flexfrank**
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns#2947610

### CODE REVIEW

**Comment by flexfrank** [comment]
I added InvalidPushType error.
Thanks.

**Comment by cubicdaiya** [comment]
@RobotsAndPencils @nathany If there is no problem, could you approve and merge this?

**Comment by junpayment** [comment]
@RobotsAndPencils @nathany
The release of ios13 is approaching 9/19.
I hope you will merge before that.

**Comment by nathany** [comment]
Thanks. We should probably add something to the README in the headers section.

**Comment by nathany** [comment]
There were a number of lint issues:

```
push/header.go:32:6: exported type PushType should have comment or be unexported
push/header.go:32:6: type name will be used as push.PushType by other packages, and that stutters; consider calling this Type
push/header.go:35:2: exported const PushTypeAlert should have comment (or a comment on this block) or be unexported
```

I've changed the API slightly.

**Comment by nathany** [comment]
release tagged: [0.14.0](https://github.com/RobotsAndPencils/buford/releases/tag/v0.14.0)

**Pull request merged**
