### PR TITLE
Fix for cert verify in Go 1.10

### PR DESCRIPTION
**Pull request by kmcrawford**
In Go 1.10  returns: certificate specifies an incompatible key usage: asn1.ObjectIdentifier{1, 3, 6, 1, 5, 5, 7, 3, 1} for APNS cert. This code change will catch and ignore this error.

### CODE REVIEW

**Comment by kmcrawford** [comment]
I am not sure why travis failed to build.  I have tested this locally back to 1.7.5

**Comment by nathany** [comment]
This is the TravisCI failure:

```
 --- FAIL: TestNewClient (0.10s)
	service_test.go:22: certificate has expired or is not yet valid
```

**Comment by kmcrawford** [comment]
It looks like the cert used in the test has expired. This is irrelevant of the code change.

**Comment by kmcrawford** [comment]
@nathany I updated the expired cert to a valid one.  The tests now pass.

**Comment by nathany** [comment]
Thank you Ken!

**Pull request merged**
